#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 17 22:47:38 2019

@author: jingjingli
"""

import requests
from bs4 import BeautifulSoup
import time
i = 0
time = time.strftime('%Y/%m/%d')
url = 'https://www.gocomics.com/pearlsbeforeswine/{}'.format(time)
while i < 10:
    res = requests.get(url)
    res.raise_for_status()
    soup = BeautifulSoup(res.text)
    
    comic_div = soup.select('picture.item-comic-image')
    
    image_url = comic_div[0].contents[0].attrs['src']
    image_res = requests.get(image_url)
    image_res.raise_for_status()
    
    title_div = soup.select('div.gc-container h1.m-0')
    filename = title_div[0].contents[0]
    image_file = open(filename, 'wb')
    for chunk in  image_res.iter_content(100000):
        image_file.write(chunk)
    image_file.close()
    
    prev_link = soup.select('a[role="button"]')[4]
    url = 'https://www.gocomics.com'+ prev_link.get('href')
    #print(url)
    i+=1
     
    
    